<#
.SYNOPSIS
    "Vault registration" phase: CyberArk "Registration" stage via Execute-Stage.ps1,
    with the Vault address (cluster,DR) injected from zones.psd1.

.DESCRIPTION
    Goal: be able to drop in a NEW CyberArk source without ever hand-editing its
    RegistrationConfig.xml. The Vault address ("clusterIp,drIp" format) comes from
    zones.psd1; the script patches a COPY (under state\) and runs Execute-Stage on
    it - the media stays intact.

    - The Vault install/admin account password is provided via -spwdObj
      (SecureString), retrieved beforehand through the PVWA API.
    - The location of the Vault address field in the XML is configurable
      (settings.psd1 Registration.VaultAddressXPath / VaultAddressAttribute), to
      adapt to the media's schema without touching the code.
#>

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

function Invoke-PSMRegister {
    [CmdletBinding(SupportsShouldProcess)]
    param(
        [Parameter(Mandatory)] $Settings,
        [Parameter(Mandatory)] [string] $SourcesRoot,
        [pscredential] $InstallCredential,   # password injected via -spwdObj
        [string] $VaultAddress               # "clusterIp,drIp" (from zones.psd1)
    )
    # Vault address driven by the zone: DYNAMIC injection into a patched copy of
    # RegistrationConfig.xml (media intact), through the generic stage engine.
    # The field's location in the XML is configurable (settings.psd1 Registration.*).
    $extra = $null
    if ($VaultAddress) {
        $xpath = $Settings.Registration.VaultAddressXPath
        $attr  = $Settings.Registration.VaultAddressAttribute
        if (-not $xpath) {
            throw "settings.psd1: Registration.VaultAddressXPath not set."
        }
        $extra = @{ $xpath = @{ Attribute = $attr; Value = $VaultAddress } }
    }
    else {
        Write-PSMLog -Level WARN -Message "No zone Vault address (VaultAddress): using the media's RegistrationConfig.xml as-is."
    }

    $stage = Resolve-PSMStageConfig -Settings $Settings -SourcesRoot $SourcesRoot `
                -StageKey 'Registration' -ExtraInjections $extra

    $securePwd = if ($InstallCredential) { $InstallCredential.Password } else { $null }

    return Invoke-PSMStage -StageName 'Registration' `
                           -ExecuteStagePath $stage.ExecuteStage `
                           -ConfigFilePath   $stage.ConfigFilePath `
                           -VaultPassword    $securePwd
}

function New-PSMComponentPassword {
    <#
        Random password for a component Vault user (password-sync flow).
        64-character charset (A-Za-z0-9 plus '-' and '_'): unbiased modulo
        mapping, and CLI-safe (the value goes on the CreateCredFile.exe command
        line - no quotes, spaces or '&'). Registered as a secret for log masking.
    #>
    [CmdletBinding()]
    param([int] $Length = 32)
    $charset = [char[]]'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-_'
    $rng     = New-Object System.Security.Cryptography.RNGCryptoServiceProvider
    try {
        $bytes = New-Object byte[] $Length
        $rng.GetBytes($bytes)
        $newPwd = -join ($bytes | ForEach-Object { $charset[$_ % $charset.Count] })
    }
    finally { $rng.Dispose() }
    if (Get-Command Register-PSMSecret -ErrorAction SilentlyContinue) { Register-PSMSecret -Secret $newPwd }
    return $newPwd
}

function Update-PSMCredFile {
    <#
        Regenerates a CyberArk cred file with CreateCredFile.exe (<PsmDir>\Vault),
        MIRRORING the protections of the existing file (generated by the
        registration): /AppType when the current file carries an AppType= line,
        /EntropyFile /DPAPIMachineProtection when a '<cred>.entropy' file sits
        next to it. '.orig' backup made only once.
        Used by the password-sync flow (Resolve-PSMExistingComponentUser).
    #>
    [CmdletBinding(SupportsShouldProcess)]
    param(
        [Parameter(Mandatory)] $Settings,
        [Parameter(Mandatory)] [string] $CredPath,
        [Parameter(Mandatory)] [string] $UserName,
        [Parameter(Mandatory)] [string] $Password
    )
    $exe = Join-Path (Get-PSMInstallPaths -Settings $Settings).PsmDir 'Vault\CreateCredFile.exe'
    if (-not (Test-Path $exe)) {
        throw "Update-PSMCredFile: CreateCredFile.exe not found ($exe) - check Install.InstallDir."
    }
    if (-not (Test-Path $CredPath)) { throw "Update-PSMCredFile: cred file not found: $CredPath." }

    # Mirror the protections of the file generated by the registration.
    $extra = @()
    $m = [regex]::Match((Get-Content -Path $CredPath -Raw), '(?im)^\s*AppType\s*=\s*(.+?)\s*$')
    if ($m.Success) { $extra += @('/AppType', $m.Groups[1].Value) }
    if (Test-Path "$CredPath.entropy") { $extra += @('/EntropyFile', '/DPAPIMachineProtection') }

    if (-not $PSCmdlet.ShouldProcess($CredPath, "Regenerate the cred file (Username=$UserName)")) { return $false }
    $backup = "$CredPath.orig"
    if (-not (Test-Path $backup)) { Copy-Item -Path $CredPath -Destination $backup -Force }

    Write-PSMLog -Level INFO -Message ("CreateCredFile: `"$exe`" `"$CredPath`" Password /Username $UserName /Password *** " + ($extra -join ' '))
    $out = & $exe $CredPath Password /Username $UserName /Password $Password @extra 2>&1
    if ($LASTEXITCODE -ne 0) {
        throw "CreateCredFile.exe failed (exit code $LASTEXITCODE): $out"
    }
    # Sanity check: the regenerated file must carry the expected user.
    if ((Get-Content -Path $CredPath -Raw) -notmatch ('(?im)^\s*Username\s*=\s*' + [regex]::Escape($UserName) + '\s*$')) {
        throw "Update-PSMCredFile: '$CredPath' does not carry Username=$UserName after regeneration. CreateCredFile output: $out"
    }
    Write-PSMLog -Level INFO -Message "Cred file regenerated: $CredPath (Username=$UserName, password synced with the Vault)."
    return $true
}

function Resolve-PSMExistingComponentUser {
    <#
        Handles a NAME COLLISION on the Vault side: the target component name
        (e.g. PSM-<HOST>) already exists, leftover from a previous deployment of
        the SAME server (wiping/reverting the machine never removes the Vault
        users). Such a stale user is exactly what causes the "password mismatch"
        at PSM service restart: the local cred file and the Vault user then come
        from different cycles.

        Resolution driven by settings.psd1 Registration.ExistingAccountAction:
          - Ask (default) : interactive choice (Overwrite recommended);
          - Overwrite     : DELETE the stale user; the freshly registered one is
                            then renamed into its place (cred file keeps its
                            valid secret + the CURRENT registration's Safe
                            memberships) -> most consistent end state;
          - ResetPassword : KEEP the stale user, reset its password (PVWA API)
                            and regenerate the local cred file with it; the
                            freshly registered orphan is deleted. The kept user
                            retains its OLD Safe memberships;
          - Fail          : stop with the manual-cleanup error (historic behavior).

        Returns $true when the collision was fully handled by the password-sync
        (nothing left to rename for this target), $false when the way is clear
        for the normal rename (no collision, or stale user deleted).
    #>
    [CmdletBinding(SupportsShouldProcess)]
    param(
        [Parameter(Mandatory)] $Settings,
        [Parameter(Mandatory)] $Session,
        [Parameter(Mandatory)] $Target,       # @{ CredPath; OldName; NewName }
        [string] $Action = 'Ask',
        [switch] $NonInteractive
    )
    $existing = @(Find-PvwaUser -Session $Session -Search $Target.NewName | Where-Object { $_.username -eq $Target.NewName })
    if ($existing.Count -eq 0) { return $false }   # no collision: normal rename

    Write-PSMLog -Level WARN -Message ("Vault user '$($Target.NewName)' ALREADY exists (leftover from a previous " +
        'installation of this server): the local cred file and this user come from different cycles - ' +
        'this is what causes the logon/password mismatch when the PSM service restarts.')

    if ($Action -eq 'Ask') {
        if ($NonInteractive) {
            throw ("Rename-PSMComponentAccounts: user '$($Target.NewName)' already exists on the Vault side and " +
                   "Registration.ExistingAccountAction='Ask' cannot prompt in NonInteractive mode. Set the policy in " +
                   "settings.psd1 ('Overwrite' | 'ResetPassword' | 'Fail') or run interactively.")
        }
        $choices = [System.Management.Automation.Host.ChoiceDescription[]]@(
            (New-Object System.Management.Automation.Host.ChoiceDescription '&Overwrite',
                ("Delete the existing Vault user '$($Target.NewName)' and rename the freshly registered " +
                 "'$($Target.OldName)' into its place (recommended: keeps the current registration's Safe memberships and cred file)."))
            (New-Object System.Management.Automation.Host.ChoiceDescription '&Password sync',
                ("Keep the existing Vault user '$($Target.NewName)': reset its password and rewrite the local cred file " +
                 "with it; the freshly registered '$($Target.OldName)' is deleted (the kept user retains its OLD Safe memberships)."))
            (New-Object System.Management.Automation.Host.ChoiceDescription '&Abort',
                'Stop the deployment (manual cleanup, historic behavior).')
        )
        $picked = $Host.UI.PromptForChoice("Existing Vault user: $($Target.NewName)",
                     'How should the existing component user be handled?', $choices, 0)
        $Action = @('Overwrite', 'ResetPassword', 'Fail')[$picked]
    }

    switch ($Action) {
        'Overwrite' {
            Remove-PvwaUser -Session $Session -UserName $Target.NewName | Out-Null
            Write-PSMLog -Level OK -Message ("Vault: stale user '$($Target.NewName)' deleted (Overwrite) - " +
                "the freshly registered '$($Target.OldName)' will take its place.")
            return $false   # way clear for the normal rename
        }
        'ResetPassword' {
            $newPwd = New-PSMComponentPassword
            $secure = ConvertTo-SecureString $newPwd -AsPlainText -Force
            Reset-PvwaUserPassword -Session $Session -UserName $Target.NewName -NewPassword $secure | Out-Null
            Write-PSMLog -Level INFO -Message "Vault: password of the kept user '$($Target.NewName)' reset."
            Update-PSMCredFile -Settings $Settings -CredPath $Target.CredPath -UserName $Target.NewName -Password $newPwd | Out-Null
            try {
                Remove-PvwaUser -Session $Session -UserName $Target.OldName | Out-Null
                Write-PSMLog -Level INFO -Message "Vault: freshly registered orphan '$($Target.OldName)' deleted."
            }
            catch {
                Write-PSMLog -Level WARN -Message ("Orphan '$($Target.OldName)' not deleted ($($_.Exception.Message)) - " +
                    'remove it manually (PVWA > Administration > Users).')
            }
            Write-PSMLog -Level WARN -Message ("'$($Target.NewName)' kept with its OLD Safe memberships: verify they " +
                'still match what the current registration would have granted.')
            return $true    # fully handled: nothing left to rename for this target
        }
        default {
            throw ("Rename-PSMComponentAccounts: user '$($Target.NewName)' ALREADY exists on the Vault side " +
                   "(leftover from a previous installation of this server). Delete it (PVWA/PrivateArk), " +
                   "along with the old orphaned PSMApp_/PSMGw_ users, then relaunch - or set " +
                   "Registration.ExistingAccountAction = 'Overwrite' / 'ResetPassword' to automate it.")
        }
    }
}

function Rename-PSMComponentAccounts {
    <#
        Aligns the PSM component accounts with the team's naming convention
        (procedure previously applied by hand on the existing PSMs, automated here):
          - "App" user PSMApp_<hex>  -> PSM-<HOSTNAME>   (configurable pattern)
          - "Gw"  user PSMGw_<hex>   -> PSMA<HOSTNAME>
        RegisterComponent.exe offers NO naming parameter for PSM: the rename
        therefore happens AFTER the registration, in 4 steps:
          1. rename of the Vault users (PVWA API, admin session reused);
          2. update of the Username= line in the cred files (the password does not
             change, the encrypted Secret stays valid; .orig backup);
          3. update of basic_psm.ini (PSMServerId / PSMServerAdminId);
          4. PSM service stopped during the operation then restarted if it was running.

        Driven by settings.psd1 Registration.RenameComponents ($true/$false).
        Idempotent: when the cred files already carry the target names, does nothing.
        When the TARGET name already exists on the Vault side (leftover from a
        previous deployment of the same server), the collision is resolved per
        Registration.ExistingAccountAction (Ask/Overwrite/ResetPassword/Fail) -
        see Resolve-PSMExistingComponentUser.
    #>
    [CmdletBinding(SupportsShouldProcess)]
    param(
        [Parameter(Mandatory)] $Settings,
        [Parameter(Mandatory)] $Session,     # open PVWA session (Connect-PvwaSession)
        [switch] $NonInteractive             # forbids the 'Ask' collision prompt
    )
    $regCfg = Get-PSMConfigValue -Config $Settings -Key 'Registration'
    if (-not $regCfg -or -not (Get-PSMConfigValue -Config $regCfg -Key 'RenameComponents')) { return $false }
    # Policy when the TARGET name already exists on the Vault side (leftover from
    # a previous deployment of the same server) - see Resolve-PSMExistingComponentUser.
    $existingAction = Get-PSMConfigValue -Config $regCfg -Key 'ExistingAccountAction'
    if (-not $existingAction) { $existingAction = 'Ask' }
    if ($existingAction -notin @('Ask', 'Overwrite', 'ResetPassword', 'Fail')) {
        throw "settings.psd1: Registration.ExistingAccountAction='$existingAction' invalid (expected: Ask | Overwrite | ResetPassword | Fail)."
    }
    # basic_psm.ini PSMServerId/PSMServerAdminId must stay ALIGNED with the "PSM
    # Server" object in PVWA (PVConfiguration), which the REST API cannot rename.
    # Their update is therefore OPT-IN (Registration.RenameServerIds) and must be
    # paired with the manual object rename in PVWA Options (as done in production).
    $renameIds = [bool](Get-PSMConfigValue -Config $regCfg -Key 'RenameServerIds')

    $hostName   = $env:COMPUTERNAME.ToUpper()
    $appPattern = Get-PSMConfigValue -Config $regCfg -Key 'AppUserPattern'
    $gwPattern  = Get-PSMConfigValue -Config $regCfg -Key 'GwUserPattern'
    if (-not $appPattern) { $appPattern = 'PSM-{HOSTNAME}' }
    if (-not $gwPattern)  { $gwPattern  = 'PSMA{HOSTNAME}' }
    $appNew = $appPattern.Replace('{HOSTNAME}', $hostName)
    $gwNew  = $gwPattern.Replace('{HOSTNAME}', $hostName)

    # basic_psm.ini -> cred file paths + IDs to update.
    $iniPath = Join-Path (Get-PSMInstallPaths -Settings $Settings).PsmDir 'basic_psm.ini'
    if (-not (Test-Path $iniPath)) {
        throw "Rename-PSMComponentAccounts: basic_psm.ini not found ($iniPath) - is the PSM installed?"
    }
    $ini = Get-Content -Path $iniPath -Raw
    $credPaths = @{}
    foreach ($k in 'PSMAppCredFile', 'PSMGWCredFile') {
        $m = [regex]::Match($ini, '(?im)^\s*' + $k + '\s*=\s*"?([^"\r\n]+?)"?\s*$')
        if (-not $m.Success) { throw "Rename-PSMComponentAccounts: key '$k' not found in $iniPath." }
        $credPaths[$k] = $m.Groups[1].Value
    }

    # Current names read from the cred files (local source of truth).
    $targets = @(
        @{ CredPath = $credPaths['PSMAppCredFile']; NewName = $appNew; IniKey = 'PSMServerId' }
        @{ CredPath = $credPaths['PSMGWCredFile'];  NewName = $gwNew;  IniKey = 'PSMServerAdminId' }
    )
    foreach ($t in $targets) {
        if (-not (Test-Path $t.CredPath)) { throw "Cred file not found: $($t.CredPath) (registration finished?)" }
        $m = [regex]::Match((Get-Content -Path $t.CredPath -Raw), '(?im)^\s*Username\s*=\s*(.+?)\s*$')
        if (-not $m.Success) { throw "'Username=' line not found in $($t.CredPath)." }
        $t.OldName = $m.Groups[1].Value
    }

    if (-not (@($targets | Where-Object { $_.OldName -cne $_.NewName }))) {
        Write-PSMLog -Level OK -Message "Component accounts already match the convention ($appNew / $gwNew)."
        return $false
    }
    if (-not $PSCmdlet.ShouldProcess("$($targets[0].OldName) -> $appNew ; $($targets[1].OldName) -> $gwNew",
                                     'Rename the PSM component accounts')) { return $false }

    # Service stopped during the operation (it authenticates with the cred files).
    $svc = Get-Service -Name 'Cyberark Privileged Session Manager' -ErrorAction SilentlyContinue
    $wasRunning = $svc -and $svc.Status -eq 'Running'
    if ($wasRunning) {
        Write-PSMLog -Level INFO -Message 'Stopping the PSM service for the component account rename...'
        Stop-Service -Name 'Cyberark Privileged Session Manager' -Force
    }

    foreach ($t in $targets) {
        if ($t.OldName -cne $t.NewName) {
            # 0) The target name may ALREADY exist on the Vault side (leftover from
            #    a previous installation of the SAME server: wiping the machine does
            #    not remove the Vault users). Resolved per the configured policy:
            #    delete it (Overwrite) or keep it and re-sync its password with the
            #    local cred file (ResetPassword) - see Resolve-PSMExistingComponentUser.
            $handled = Resolve-PSMExistingComponentUser -Settings $Settings -Session $Session `
                          -Target $t -Action $existingAction -NonInteractive:$NonInteractive
            if (-not $handled) {
                # 1) Vault side (PVWA API).
                Rename-PvwaUser -Session $Session -UserName $t.OldName -NewUserName $t.NewName | Out-Null
                Write-PSMLog -Level INFO -Message "Vault: user '$($t.OldName)' renamed to '$($t.NewName)'."
                # 2) Cred file: Username= line (password unchanged), .orig backup.
                $backup = "$($t.CredPath).orig"
                if (-not (Test-Path $backup)) { Copy-Item -Path $t.CredPath -Destination $backup -Force }
                $raw = Get-Content -Path $t.CredPath -Raw
                $raw = ([regex]'(?im)^(\s*Username\s*=\s*).+?\s*$').Replace($raw, ('${1}' + $t.NewName), 1)
                Set-Content -Path $t.CredPath -Value $raw -NoNewline
                Write-PSMLog -Level INFO -Message "Cred file updated: $($t.CredPath) (Username=$($t.NewName))."
            }
        }
        # 3) basic_psm.ini: matching ID (OPT-IN, see RenameServerIds above).
        if ($renameIds) {
            if ($ini -notmatch ('(?im)^\s*' + $t.IniKey + '\s*=\s*"')) {
                throw "Rename-PSMComponentAccounts: key '$($t.IniKey)' not found in $iniPath."
            }
            $ini = ([regex]('(?im)^(\s*' + $t.IniKey + '\s*=\s*")[^"]*(")')).Replace($ini, ('${1}' + $t.NewName + '${2}'), 1)
        }
    }
    if ($renameIds) {
        $iniBackup = "$iniPath.orig"
        if (-not (Test-Path $iniBackup)) { Copy-Item -Path $iniPath -Destination $iniBackup -Force }
        Set-Content -Path $iniPath -Value $ini -NoNewline
        Write-PSMLog -Level WARN -Message ("basic_psm.ini updated (PSMServerId=$appNew, PSMServerAdminId=$gwNew). " +
            "REQUIRED PAIRED STEP: rename the PSM server object ID accordingly in PVWA " +
            "(Administration > Options > Privileged Session Management > Configured PSM Servers), " +
            "otherwise the PSM will not find its server configuration.")
    }
    else {
        Write-PSMLog -Level INFO -Message ("basic_psm.ini PSMServerId/PSMServerAdminId left unchanged " +
            "(Registration.RenameServerIds=false): they stay aligned with the PSM server object in PVWA Options.")
    }

    if ($wasRunning) {
        Start-Service -Name 'Cyberark Privileged Session Manager'
        Write-PSMLog -Level INFO -Message 'PSM service restarted.'
    }
    Write-PSMLog -Level OK -Message "Component accounts renamed: $appNew / $gwNew."
    return $true
}

Export-ModuleMember -Function Invoke-PSMRegister, Rename-PSMComponentAccounts, `
                              Resolve-PSMExistingComponentUser, New-PSMComponentPassword, Update-PSMCredFile
